#!/bin/bash

# Wait a moment to ensure displays are detected
sleep 2

# Get list of connected displays
CONNECTED=$(xrandr | grep " connected" | cut -d' ' -f1)

# Set external and internal output names 
EXTERNAL="HDMI-1"
INTERNAL="eDP-1"

if echo $CONNECTED | grep -q "$EXTERNAL"; then
    xrandr --output "$EXTERNAL" --primary --mode 1920x1080 --pos 0x0 --rotate normal \
	   --output "$INTERNAL" --off
else
    xrandr --output "$INTERNAL" --primary --auto
fi

exec $1 # Launch the real session
